Console.WriteLine("Welcome To My Calculator Project .");
Console.Write("Please Enter the First Number: ");
int num1 = int.Parse(Console.ReadLine());
Console.Write("pleae Enter the Second Number: ");
int num2 = int.Parse(Console.ReadLine());
var addition = num1 + num2;
var subtraction = num1 - num2;
var multiplication = num1 * num2;
var division = num1 / num2;
Console.WriteLine($"The Addition Two Numbers are: {addition}");
Console.WriteLine($"The subtraction Two Numbers are: {subtraction}");
Console.WriteLine($"The multiplication Two Numbers are: {multiplication}");